Make tests dependent on publish (#364)

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -63,7 +63,7 @@ jobs:
 
 
   test:
-    needs: [lint]
+    needs: [lint, publish_to_branch]
     name: Test
     env:
       CI: true
@@ -136,9 +136,13 @@ jobs:
       run: echo "HAS_CHANGES=$(git status --porcelain | wc -l | xargs echo)" >> $GITHUB_ENV
     - name: Commit changes
       if: env.HAS_CHANGES != '0'
+      # If we have changes, we push them and then fail out. This prevents
+      # us from running more testing than we want since the push will
+      # trigger another test run anyway.
       run: |
         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
         git config user.name "$GITHUB_ACTOR"
         git add dist
         git commit -m "Updating branch with build artifacts (https://github.com/Khan/render-gateway/actions/runs/${{ github.run_id }})"
         git push
+        exit 1
